import { UserProfile, EventItem } from '../types';

export const INITIAL_ATHLETES: UserProfile[] = [
  {
    uid: 'kevoie-bailey',
    email: 'kevoie.bailey@example.com',
    displayName: 'Kevoie Bailey',
    role: 'athlete',
    isVerified: true,
    sport: 'Football',
    jerseyNumber: '#7',
    teamName: 'North Jersey Lightning',
    gradYear: '2027',
    highSchool: "St. Peter's Prep",
    state: 'NJ',
    position: 'QB / ATH',
    height: "6'2\"",
    weight: '195 lbs',
    gpa: '3.9',
    bio: 'Dual-Threat 4-Star Quarterback & Athlete. 4.42 40-yd speed, elite arm velocity, and high Football IQ. Led North Jersey Lightning to state title with 2,850 passing yards & 34 TDs.',
    avatarUrl: 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@kevoie.qb7',
      twitter: '@kevoie_bailey',
      tiktok: '@kevoie_highlights'
    },
    stats: {
      passingYards: 2850,
      rushingYards: 720,
      receptions: 0,
      flagPulls: 0,
      interceptions: 4,
      gamesPlayed: 11
    } as any,
    performanceMetrics: {
      speed: 96,
      strength: 88,
      agility: 94,
      stamina: 92,
      vertical: 91,
      iq: 98
    },
    mediaUrls: [
      {
        id: 'vid-kb-1',
        title: '4K Official Junior Highlight Vault | 34 Passing TDs & 12 Rushing TDs',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        platform: 'youtube',
        createdAt: '2026-07-28'
      },
      {
        id: 'vid-kb-2',
        title: 'State Championship Game Winning Drive Highlights',
        url: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
        platform: 'youtube',
        createdAt: '2026-07-15'
      }
    ],
    gameLogs: [
      {
        id: 'glog-kb-1',
        athleteUid: 'kevoie-bailey',
        gameDate: '2026-07-26',
        sport: 'Flag Football',
        opponent: 'Bergen Catholic Crusaders',
        gameResult: 'W',
        teamScore: 38,
        opponentScore: 31,
        isHomeGame: true,
        location: 'Lightning Stadium',
        notes: 'Clutch 4th quarter 65-yard TD pass to seal championship victory!',
        isVerified: true,
        createdAt: '2026-07-26T21:00:00.000Z',
        stats: {
          passingYards: 340,
          rushingYards: 85,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          flagPulls: 0,
          interceptions: 0
        } as any
      },
      {
        id: 'glog-kb-2',
        athleteUid: 'kevoie-bailey',
        gameDate: '2026-07-19',
        sport: 'Flag Football',
        opponent: 'Don Bosco Prep Ironmen',
        gameResult: 'W',
        teamScore: 42,
        opponentScore: 28,
        isHomeGame: false,
        location: 'Ironmen Arena',
        notes: 'Recorded 3 passing TDs and 2 rushing TDs in semi-final matchup.',
        isVerified: true,
        createdAt: '2026-07-19T20:00:00.000Z',
        stats: {
          passingYards: 295,
          rushingYards: 110,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          flagPulls: 0,
          interceptions: 1
        } as any
      },
      {
        id: 'glog-kb-3',
        athleteUid: 'kevoie-bailey',
        gameDate: '2026-07-12',
        sport: 'Flag Football',
        opponent: 'Paramus Catholic Paladins',
        gameResult: 'W',
        teamScore: 35,
        opponentScore: 14,
        isHomeGame: true,
        location: 'Lightning Stadium',
        notes: 'Completed 18/22 passes with zero turnovers.',
        isVerified: true,
        createdAt: '2026-07-12T19:30:00.000Z',
        stats: {
          passingYards: 280,
          rushingYards: 45,
          receptions: 0,
          receivingYards: 0,
          receivingTds: 0,
          flagPulls: 0,
          interceptions: 0
        } as any
      }
    ],
    createdAt: '2026-01-01',
    updatedAt: '2026-08-01'
  },
  {
    uid: 'ath-1',
    email: 'jayden.carter@example.com',
    displayName: 'Jayden "Fly" Carter',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'St. Anthony Prep',
    state: 'NJ',
    position: 'Point Guard',
    height: "6'2\"",
    weight: '185 lbs',
    gpa: '3.8',
    bio: 'Elite 4-star PG. Fast in transition with high basketball IQ and tight ball-handling. Looking for Division 1 programs with strong sports management programs.',
    avatarUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@jaydencarter_0',
      twitter: '@jayden_hoops',
      tiktok: '@jaydenfly'
    },
    stats: {
      points: 24.5,
      rebounds: 6.2,
      assists: 8.4,
      steals: 2.8,
      blocks: 0.6,
      gamesPlayed: 28
    },
    performanceMetrics: {
      speed: 92,
      strength: 84,
      agility: 95,
      stamina: 90,
      vertical: 94,
      iq: 96
    },
    mediaUrls: [
      {
        id: 'vid-1',
        title: 'Junior Season Mixtape | 24.5 PPG & Insane Dunk Package',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        platform: 'youtube',
        createdAt: '2026-06-12'
      },
      {
        id: 'vid-2',
        title: 'Game Winner vs Bergen Catholic Highlights',
        url: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
        platform: 'youtube',
        createdAt: '2026-05-18'
      }
    ],
    gameLogs: [
      {
        id: 'glog-101',
        athleteUid: 'ath-1',
        gameDate: '2026-07-22',
        sport: 'Basketball',
        opponent: 'Bergen Catholic Crusaders',
        gameResult: 'W',
        teamScore: 82,
        opponentScore: 78,
        isHomeGame: true,
        location: 'St. Anthony Main Gym',
        notes: 'Hit buzzer-beater stepback 3-pointer with 1.2s remaining! Finished with double-double.',
        highlightVideoUrl: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
        isVerified: true,
        createdAt: '2026-07-22T21:00:00.000Z',
        stats: {
          points: 32,
          rebounds: 8,
          assists: 10,
          steals: 4,
          blocks: 1,
          fgMade: 12,
          fgAttempted: 19,
          threeMade: 4,
          ftMade: 4,
          ftAttempted: 5
        }
      },
      {
        id: 'glog-102',
        athleteUid: 'ath-1',
        gameDate: '2026-07-15',
        sport: 'Basketball',
        opponent: 'Camden High Panthers',
        gameResult: 'W',
        teamScore: 74,
        opponentScore: 68,
        isHomeGame: false,
        location: 'Camden High Fieldhouse',
        notes: 'Heavy full-court pressure. Controlled tempo in 4th quarter with clutch free throws.',
        isVerified: true,
        createdAt: '2026-07-15T20:30:00.000Z',
        stats: {
          points: 26,
          rebounds: 5,
          assists: 7,
          steals: 3,
          blocks: 0,
          fgMade: 9,
          fgAttempted: 16,
          threeMade: 3,
          ftMade: 5,
          ftAttempted: 6
        }
      },
      {
        id: 'glog-103',
        athleteUid: 'ath-1',
        gameDate: '2026-07-08',
        sport: 'Basketball',
        opponent: 'Don Bosco Prep Ironmen',
        gameResult: 'L',
        teamScore: 65,
        opponentScore: 70,
        isHomeGame: true,
        location: 'St. Anthony Main Gym',
        notes: 'Tight defensive battle. Led team in scoring despite double-teams.',
        isVerified: true,
        createdAt: '2026-07-08T19:45:00.000Z',
        stats: {
          points: 22,
          rebounds: 6,
          assists: 8,
          steals: 2,
          blocks: 1,
          fgMade: 8,
          fgAttempted: 18,
          threeMade: 2,
          ftMade: 4,
          ftAttempted: 4
        }
      }
    ],
    createdAt: '2026-01-10',
    updatedAt: '2026-07-20'
  },
  {
    uid: 'ath-2',
    email: 'maya.sanchez@example.com',
    displayName: 'Maya "Speedy" Sanchez',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2025',
    highSchool: 'Paramus Catholic',
    state: 'NJ',
    position: 'QB / Rusher',
    height: "5'7\"",
    weight: '140 lbs',
    gpa: '3.9',
    bio: 'Varsity Dual-Threat QB & Lead Flag Puller. 2x All-State Champion. High accuracy under pressure and electric open-field agility.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@maya.ff.qb',
      tiktok: '@mayasanchez_qb'
    },
    stats: {
      passingYards: 2450,
      rushingYards: 890,
      receptions: 12,
      flagPulls: 68,
      interceptions: 14,
      gamesPlayed: 18
    },
    performanceMetrics: {
      speed: 97,
      strength: 78,
      agility: 98,
      stamina: 92,
      vertical: 88,
      iq: 94
    },
    mediaUrls: [
      {
        id: 'vid-3',
        title: '2026 State Championship Flag Football Highlights',
        url: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
        platform: 'youtube',
        createdAt: '2026-06-20'
      }
    ],
    createdAt: '2026-02-14',
    updatedAt: '2026-07-22'
  },
  {
    uid: 'ath-3',
    email: 'marcus.vance@example.com',
    displayName: 'Marcus Vance',
    role: 'athlete',
    sport: 'Lacrosse',
    gradYear: '2027',
    highSchool: 'Delbarton School',
    state: 'NJ',
    position: 'Attack / Midfield',
    height: "6'1\"",
    weight: '190 lbs',
    gpa: '3.7',
    bio: 'Dominant righty attackman with lethal step-down shot (92mph). High lacrosse IQ and tenacious ride downfield.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@marcusvance_lax',
      twitter: '@marcus_lax27'
    },
    stats: {
      goals: 54,
      assists: 31,
      groundBalls: 42,
      drawControls: 18,
      causedTurnovers: 12,
      gamesPlayed: 20
    },
    mediaUrls: [
      {
        id: 'vid-4',
        title: 'Sophomore Year Goal Compilation & Dodging Breakdown',
        url: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
        platform: 'youtube',
        createdAt: '2026-05-30'
      }
    ],
    createdAt: '2026-03-01',
    updatedAt: '2026-07-15'
  },
  {
    uid: 'ath-4',
    email: 'sydney.brooks@example.com',
    displayName: 'Sydney Brooks',
    role: 'athlete',
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'Christ the King',
    state: 'NY',
    position: 'Shooting Guard',
    height: "5'11\"",
    weight: '155 lbs',
    gpa: '4.0',
    bio: 'Sharpshooter from beyond the arc (44% 3PT). Explosive defender and vocal team captain.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@sydney_buckets',
      tiktok: '@sydneybrooks26'
    },
    stats: {
      points: 21.8,
      rebounds: 5.1,
      assists: 4.6,
      steals: 3.1,
      blocks: 1.1,
      gamesPlayed: 24
    },
    mediaUrls: [
      {
        id: 'vid-5',
        title: '3PT Shooting Clinic - 8 Threes in One Game',
        url: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
        platform: 'youtube',
        createdAt: '2026-04-12'
      }
    ],
    createdAt: '2026-02-10',
    updatedAt: '2026-07-10'
  },
  {
    uid: 'ath-5',
    email: 'devon.reed@example.com',
    displayName: 'Devon "Deuce" Reed',
    role: 'athlete',
    sport: 'Flag Football',
    gradYear: '2028',
    highSchool: 'St. Peter\'s Prep',
    state: 'NJ',
    position: 'Wide Receiver',
    height: "6'0\"",
    weight: '170 lbs',
    gpa: '3.6',
    bio: 'Sub-4.5 40-yard dash velocity. Elite route running and sticky hands on deep passing routes.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    social: {
      instagram: '@devonreed.2',
      tiktok: '@deucereed'
    },
    stats: {
      passingYards: 150,
      rushingYards: 420,
      receptions: 58,
      flagPulls: 32,
      interceptions: 8,
      gamesPlayed: 16
    },
    mediaUrls: [],
    createdAt: '2026-04-05',
    updatedAt: '2026-07-18'
  },
  {
    uid: 'csv-mem-1',
    email: 'kevoieb.quality@gmail.com',
    displayName: 'Kevoie Bailey',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'St. Anthony Prep',
    state: 'NJ',
    position: 'Point Guard / Shooting Guard',
    height: "6'1\"",
    weight: '180 lbs',
    gpa: '3.8',
    bio: 'Verified Just1Play Site Member. Elite ball handler with rapid court vision.',
    avatarUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@kevoie.b' },
    stats: { points: 22.4, rebounds: 5.8, assists: 7.2, steals: 2.4, blocks: 0.8, gamesPlayed: 24 },
    mediaUrls: [],
    createdAt: '2026-06-30',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-2',
    email: 'sanaiithegoat1@gmail.com',
    displayName: 'Sanaii "The Goat"',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'Camden High',
    state: 'NJ',
    position: 'Shooting Guard',
    height: "5'10\"",
    weight: '155 lbs',
    gpa: '3.7',
    bio: 'Verified Just1Play Site Member. High scoring efficiency and relentless perimeter defense.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@sanaii_goat' },
    stats: { points: 19.8, rebounds: 4.5, assists: 5.1, steals: 2.1, blocks: 0.4, gamesPlayed: 22 },
    mediaUrls: [],
    createdAt: '2026-07-13',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-3',
    email: 'j.mcburrows23@gmail.com',
    displayName: 'Jake McBurrows',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2027',
    highSchool: 'Bergen Catholic',
    state: 'NJ',
    position: 'Small Forward',
    height: "6'4\"",
    weight: '195 lbs',
    gpa: '3.6',
    bio: 'Verified Just1Play Site Member. Versatile wing prospect with strong physical drive inside.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@jake_mcburrows' },
    stats: { points: 17.5, rebounds: 8.2, assists: 3.4, steals: 1.6, blocks: 1.2, gamesPlayed: 20 },
    mediaUrls: [],
    createdAt: '2026-07-09',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-4',
    email: 'davisxavier422@gmail.com',
    displayName: 'Xavier Davis',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Paramus Catholic',
    state: 'NJ',
    position: 'Quarterback',
    height: "6'2\"",
    weight: '185 lbs',
    gpa: '3.9',
    bio: 'Verified Just1Play Site Member. High-velocity passer with quick pocket decision-making.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@xavier_davis4' },
    stats: { passingYards: 2150, rushingYards: 640, receptions: 5, flagPulls: 30, interceptions: 12, gamesPlayed: 16 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-5',
    email: 'faa1420@yahoo.com',
    displayName: 'Frank Antonio',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2025',
    highSchool: 'Christ the King',
    state: 'NY',
    position: 'Power Forward',
    height: "6'6\"",
    weight: '210 lbs',
    gpa: '3.5',
    bio: 'Verified Just1Play Site Member. Dominant post-up player and tenacious rebounder.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@frank_antonio14' },
    stats: { points: 15.2, rebounds: 10.4, assists: 2.8, steals: 1.1, blocks: 2.1, gamesPlayed: 25 },
    mediaUrls: [],
    createdAt: '2026-07-15',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-6',
    email: 'daniellemaat09@gmail.com',
    displayName: 'Dani Maat',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Hudson Catholic',
    state: 'NJ',
    position: 'Wide Receiver / Rusher',
    height: "5'8\"",
    weight: '145 lbs',
    gpa: '4.0',
    bio: 'Verified Just1Play Site Member. Speedster receiver with elite route acceleration.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@dani_maat' },
    stats: { passingYards: 120, rushingYards: 380, receptions: 48, flagPulls: 25, interceptions: 6, gamesPlayed: 14 },
    mediaUrls: [],
    createdAt: '2026-07-18',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-7',
    email: 'marnasia1@gmail.com',
    displayName: 'Nay Marnasia',
    role: 'athlete',
    isVerified: true,
    sport: 'Lacrosse',
    gradYear: '2026',
    highSchool: 'Delbarton Prep',
    state: 'PA',
    position: 'Midfield / Attack',
    height: "5'9\"",
    weight: '150 lbs',
    gpa: '3.8',
    bio: 'Verified Just1Play Site Member. High lacrosse IQ with 90+ mph shot speed. Phone: (610) 905-3775.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@nay_marnasia' },
    stats: { goals: 42, assists: 28, groundBalls: 35, drawControls: 16, causedTurnovers: 10, gamesPlayed: 18 },
    mediaUrls: [],
    createdAt: '2026-07-13',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-8',
    email: 'ahilyiawebb@gmail.com',
    displayName: 'Ahilyia Webb',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2027',
    highSchool: 'St. Dominic Academy',
    state: 'NJ',
    position: 'Rusher / Safety',
    height: "5'7\"",
    weight: '138 lbs',
    gpa: '3.9',
    bio: 'Verified Just1Play Site Member. Defensive nightmare with record flag pulls per game.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@ahilyia_webb' },
    stats: { passingYards: 50, rushingYards: 180, receptions: 22, flagPulls: 74, interceptions: 16, gamesPlayed: 16 },
    mediaUrls: [],
    createdAt: '2026-07-13',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-9',
    email: 'emmerilsmith@gmail.com',
    displayName: 'Emmeril Smith',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'Immaculate Conception',
    state: 'NJ',
    position: 'Combo Guard',
    height: "6'0\"",
    weight: '175 lbs',
    gpa: '3.6',
    bio: 'Verified Just1Play Site Member. Sharp perimeter shooter with dynamic transition scoring.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@emmeril_smith' },
    stats: { points: 18.6, rebounds: 4.2, assists: 6.0, steals: 1.9, blocks: 0.3, gamesPlayed: 21 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-10',
    email: 'xiannavaldez21@gmail.com',
    displayName: 'Xianna Valdez',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Passaic County Tech',
    state: 'NJ',
    position: 'Quarterback',
    height: "5'8\"",
    weight: '142 lbs',
    gpa: '3.95',
    bio: 'Verified Just1Play Site Member. Precision deep passer and team captain.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@xianna_valdez21' },
    stats: { passingYards: 2320, rushingYards: 510, receptions: 8, flagPulls: 20, interceptions: 15, gamesPlayed: 18 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-11',
    email: 'heaven0304p@gmail.com',
    displayName: 'Heaven Peters',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2027',
    highSchool: 'St. Rose High',
    state: 'NJ',
    position: 'Point Guard',
    height: "5'7\"",
    weight: '135 lbs',
    gpa: '3.85',
    bio: 'Verified Just1Play Site Member. High motor PG with lock-down full-court pressure.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@heaven_peters' },
    stats: { points: 16.4, rebounds: 3.8, assists: 7.5, steals: 3.2, blocks: 0.2, gamesPlayed: 20 },
    mediaUrls: [],
    createdAt: '2026-07-10',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-12',
    email: 'aaliyah.rivera10@icloud.com',
    displayName: 'Aaliyah Rivera',
    role: 'athlete',
    isVerified: true,
    sport: 'Lacrosse',
    gradYear: '2026',
    highSchool: 'St. Anthony Prep',
    state: 'NY',
    position: 'Midfield',
    height: "5'9\"",
    weight: '148 lbs',
    gpa: '4.0',
    bio: 'Verified Just1Play Site Member. Dominant draw controls and end-to-end field speed.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@aaliyah_rivera10' },
    stats: { goals: 38, assists: 24, groundBalls: 40, drawControls: 32, causedTurnovers: 14, gamesPlayed: 17 },
    mediaUrls: [],
    createdAt: '2026-07-10',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-13',
    email: 'myadejesus4554@gmail.com',
    displayName: 'Mya De Jesus',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Union High School',
    state: 'NJ',
    position: 'Wide Receiver',
    height: "5'8\"",
    weight: '140 lbs',
    gpa: '3.75',
    bio: 'Verified Just1Play Site Member. Explosive deep target with reliable clutch hands.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@mya_dejesus' },
    stats: { passingYards: 80, rushingYards: 220, receptions: 52, flagPulls: 18, interceptions: 5, gamesPlayed: 15 },
    mediaUrls: [],
    createdAt: '2026-07-08',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-14',
    email: 'kevoiebailey@gmail.com',
    displayName: 'Kevoie Bailey (Director)',
    role: 'organization',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2025',
    highSchool: 'Just1Play Academy',
    state: 'NJ',
    position: 'Director / Founder',
    height: "6'2\"",
    weight: '190 lbs',
    gpa: '4.0',
    bio: 'Verified Just1Play Executive & Athlete Director. Phone: (201) 206-9097.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@kevoiebailey' },
    stats: { points: 25.0, rebounds: 7.0, assists: 9.0, steals: 3.0, blocks: 1.0, gamesPlayed: 30 },
    mediaUrls: [],
    createdAt: '2026-06-28',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-15',
    email: 'dmscorp@gmail.com',
    displayName: 'DMS Sports Corp',
    role: 'organization',
    isVerified: true,
    sport: 'All Sports',
    gradYear: '2025',
    highSchool: 'DMS Training Center',
    state: 'NJ',
    position: 'Training Organization',
    height: "N/A",
    weight: "N/A",
    gpa: 'N/A',
    bio: 'Verified Just1Play Partner Organization specializing in high-performance athletic testing.',
    avatarUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@dmssportscorp' },
    stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, gamesPlayed: 0 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-16',
    email: 'elelemequeen8@gmail.com',
    displayName: 'Eleleme Queen',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2027',
    highSchool: 'Lodi High School',
    state: 'NJ',
    position: 'Center / Rusher',
    height: "5'9\"",
    weight: '150 lbs',
    gpa: '3.65',
    bio: 'Verified Just1Play Site Member. Dominant line rusher with quick snap reflexes.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@eleleme_queen' },
    stats: { passingYards: 0, rushingYards: 140, receptions: 30, flagPulls: 52, interceptions: 9, gamesPlayed: 14 },
    mediaUrls: [],
    createdAt: '2026-07-08',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-17',
    email: 'st00tie3334@gmail.com',
    displayName: 'T00TIE Williams',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'Teaneck High',
    state: 'NJ',
    position: 'Point Guard',
    height: "5'11\"",
    weight: '165 lbs',
    gpa: '3.5',
    bio: 'Verified Just1Play Site Member. Fast-break wizard with elite assist-to-turnover ratio.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@t00tie_33' },
    stats: { points: 20.1, rebounds: 4.0, assists: 8.8, steals: 2.7, blocks: 0.5, gamesPlayed: 23 },
    mediaUrls: [],
    createdAt: '2026-07-13',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-18',
    email: 'jaesoccer613@gmail.com',
    displayName: 'Jae Soccer',
    role: 'athlete',
    isVerified: true,
    sport: 'Lacrosse',
    gradYear: '2026',
    highSchool: 'Clifton High',
    state: 'NJ',
    position: 'Forward / Midfield',
    height: "5'10\"",
    weight: '160 lbs',
    gpa: '3.8',
    bio: 'Verified Just1Play Site Member. High stamina field player with sniper precision.',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@jae_soccer613' },
    stats: { goals: 34, assists: 22, groundBalls: 29, drawControls: 12, causedTurnovers: 8, gamesPlayed: 16 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-19',
    email: 'vanesaborjas400@icloud.com',
    displayName: 'Vanesa Borjas',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Eastside High',
    state: 'NJ',
    position: 'Quarterback / Safety',
    height: "5'8\"",
    weight: '142 lbs',
    gpa: '3.9',
    bio: 'Verified Just1Play Site Member. Dual-threat leader with championship tournament experience.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@vanesa_borjas' },
    stats: { passingYards: 1980, rushingYards: 480, receptions: 10, flagPulls: 38, interceptions: 11, gamesPlayed: 15 },
    mediaUrls: [],
    createdAt: '2026-07-10',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-20',
    email: 'melindag0912@gmail.com',
    displayName: 'Melinda Gonzalez',
    role: 'athlete',
    isVerified: true,
    sport: 'Lacrosse',
    gradYear: '2027',
    highSchool: 'Wayne Hills High',
    state: 'NJ',
    position: 'Attack',
    height: "5'7\"",
    weight: '138 lbs',
    gpa: '3.85',
    bio: 'Verified Just1Play Site Member. Lethal dodger around the crease with high shot accuracy.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@melinda_g09' },
    stats: { goals: 45, assists: 19, groundBalls: 24, drawControls: 10, causedTurnovers: 7, gamesPlayed: 17 },
    mediaUrls: [],
    createdAt: '2026-07-16',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-21',
    email: 'aishaboundy100@gmail.com',
    displayName: 'Aisha Boundy',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2026',
    highSchool: 'West Orange High',
    state: 'NJ',
    position: 'Shooting Guard',
    height: "5'10\"",
    weight: '150 lbs',
    gpa: '3.9',
    bio: 'Verified Just1Play Site Member. Three-point specialist with high defensive IQ.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@aisha_boundy' },
    stats: { points: 19.4, rebounds: 5.2, assists: 4.8, steals: 2.3, blocks: 0.6, gamesPlayed: 22 },
    mediaUrls: [],
    createdAt: '2026-07-12',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-22',
    email: 'izzyali49@gmail.com',
    displayName: 'Izzy Ali',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2028',
    highSchool: 'Hackensack High',
    state: 'NJ',
    position: 'Safety / Rusher',
    height: "5'8\"",
    weight: '144 lbs',
    gpa: '3.7',
    bio: 'Verified Just1Play Site Member. Ball-hawking safety with 6 pick-sixes on the season.',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@izzy_ali49' },
    stats: { passingYards: 0, rushingYards: 210, receptions: 18, flagPulls: 62, interceptions: 18, gamesPlayed: 15 },
    mediaUrls: [],
    createdAt: '2026-07-27',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-23',
    email: 'ayleigordon08@gmail.com',
    displayName: 'Aylei Gordon',
    role: 'athlete',
    isVerified: true,
    sport: 'Basketball',
    gradYear: '2027',
    highSchool: 'Paterson Catholic',
    state: 'NJ',
    position: 'Small Forward',
    height: "6'1\"",
    weight: '170 lbs',
    gpa: '3.8',
    bio: 'Verified Just1Play Site Member. Smooth mid-range scorer and active glass cleaner.',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@aylei_gordon' },
    stats: { points: 17.8, rebounds: 7.9, assists: 3.9, steals: 1.8, blocks: 0.9, gamesPlayed: 20 },
    mediaUrls: [],
    createdAt: '2026-07-13',
    updatedAt: '2026-07-29'
  },
  {
    uid: 'csv-mem-24',
    email: 'adrianastar08@icloud.com',
    displayName: 'Adriana Star',
    role: 'athlete',
    isVerified: true,
    sport: 'Flag Football',
    gradYear: '2026',
    highSchool: 'Montclair High',
    state: 'NJ',
    position: 'Rusher / WR',
    height: "5'9\"",
    weight: '145 lbs',
    gpa: '3.95',
    bio: 'Verified Just1Play Site Member. Unmatched initial off-the-line burst and flag pull precision.',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social: { instagram: '@adriana_star08' },
    stats: { passingYards: 110, rushingYards: 310, receptions: 40, flagPulls: 58, interceptions: 10, gamesPlayed: 16 },
    mediaUrls: [],
    createdAt: '2026-07-25',
    updatedAt: '2026-07-29'
  }
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-101',
    title: 'Just1Play Tri-State Elite Showcase Combine',
    sport: 'All Sports',
    eventType: 'Combine',
    date: '2026-08-15',
    time: '09:00 AM - 03:00 PM',
    location: 'MetLife Stadium Performance Center, East Rutherford',
    state: 'NJ',
    description: 'Official 40-yard dash, vertical jump, shuttle drill testing, and 1-on-1 position battles in front of 40+ D1, D2 & D3 College Scouts.',
    organizer: 'Just1Play Recruiting Media',
    capacity: 150,
    registeredUserIds: ['ath-1', 'ath-2', 'ath-3'],
    price: 125,
    bannerUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    isFeatured: true
  },
  {
    id: 'evt-102',
    title: 'Northeast Girls Flag Football Premier Championship',
    sport: 'Flag Football',
    eventType: 'Tournament',
    date: '2026-08-22',
    time: '10:00 AM - 06:00 PM',
    location: 'Iron Peak Sports & Events, Hillsborough',
    state: 'NJ',
    description: '7v7 Championship tournament featuring high school teams across NJ, NY, and PA with high-definition video coverage.',
    organizer: 'Just1Play League Media',
    capacity: 80,
    registeredUserIds: ['ath-2', 'ath-5'],
    price: 75,
    bannerUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&auto=format&fit=crop&q=80',
    isFeatured: true
  },
  {
    id: 'evt-103',
    title: 'Next-Gen Hoops Fall D1 Evaluation Camp',
    sport: 'Basketball',
    eventType: 'Camp',
    date: '2026-09-05',
    time: '08:30 AM - 02:00 PM',
    location: 'Barclays Center Community Court, Brooklyn',
    state: 'NY',
    description: 'Skill development drills, full-court scrimmage games with live analytics tracking, and individual scouting reports.',
    organizer: 'Just1Play Basketball Network',
    capacity: 60,
    registeredUserIds: ['ath-1', 'ath-4'],
    price: 150,
    bannerUrl: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=800&auto=format&fit=crop&q=80',
    isFeatured: false
  },
  {
    id: 'evt-104',
    title: 'Tri-State Lacrosse Prospect Tryout & Velocity Test',
    sport: 'Lacrosse',
    eventType: 'Tryout',
    date: '2026-09-12',
    time: '01:00 PM - 05:00 PM',
    location: 'Rutgers University Athletics Complex, Piscataway',
    state: 'NJ',
    description: 'Shot velocity radar testing, faceoff dominance metrics, and live scrimmage evaluations for high school recruits.',
    organizer: 'Just1Play Lax Media',
    capacity: 100,
    registeredUserIds: ['ath-3'],
    price: 90,
    bannerUrl: 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?w=800&auto=format&fit=crop&q=80',
    isFeatured: false
  }
];

export const MEDIA_PACKAGES = [
  {
    id: 'pkg-1',
    name: 'Pregame Videography & Hype Tape',
    category: 'Videography',
    basePrice: 250,
    depositPercentage: 30, // 30% deposit
    description: 'Cinematic 4K pregame warm-up coverage, custom audio mix, speed ramps, and 60-second Instagram/TikTok ready reel.',
    features: [
      '4K 60fps Pregame Field/Court Access',
      'Custom Audio Sync & Color Grade',
      'Vertical (9:16) & Horizontal Formats',
      '48-Hour Rapid Delivery'
    ]
  },
  {
    id: 'pkg-2',
    name: 'Season Highlight Reel (Full Breakdown)',
    category: 'Videography',
    basePrice: 400,
    depositPercentage: 30,
    description: 'Comprehensive college recruiting mixtape compiled from your raw footage with animated spot shadow player tracking.',
    features: [
      '3-5 Minute High-Impact Scouting Video',
      'Player Spotlight Tracking Overlay',
      'Athletic Stat Sheet Overlay',
      'Direct YouTube & Hudl Export Format'
    ]
  },
  {
    id: 'pkg-3',
    name: 'Scouting Photo Package (Action Shots)',
    category: 'Photography',
    basePrice: 180,
    depositPercentage: 30,
    description: 'High-speed professional DSLR action photography during game play and sideline emotion shots.',
    features: [
      '25+ Edited High-Res Photos',
      'Full Commercial & Social Use Rights',
      'Private Web Gallery Download',
      'Next-Day Preview Delivery'
    ]
  },
  {
    id: 'pkg-4',
    name: 'Combine Spotlight & Athletic Profile Film',
    category: 'Full Production',
    basePrice: 550,
    depositPercentage: 30,
    description: 'Full combine coverage with mic\'d up audio, combine stat verification overlays, and recruiter-focused mini doc.',
    features: [
      'Dedicated Cameraman & Mic Setup',
      'Combine Measurement Verification',
      'Mini-Documentary Interview Segment',
      'Priority Delivery to Recruiter Matrix'
    ]
  }
];

export const INITIAL_LIVE_GAMES: any[] = [
  {
    id: 'game-201',
    title: 'NJ State Championship Semi-Finals',
    sport: 'Basketball',
    status: 'Live',
    period: '3rd Quarter',
    gameClock: '04:12',
    isClockRunning: true,
    homeTeam: {
      name: 'St. Anthony Prep',
      abbreviation: 'STA',
      score: 68,
      color: '#E5B868',
      timeoutsLeft: 3,
      fouls: 4
    },
    awayTeam: {
      name: 'Bergen Catholic',
      abbreviation: 'BC',
      score: 64,
      color: '#3B82F6',
      timeoutsLeft: 2,
      fouls: 5
    },
    location: 'MetLife Arena, East Rutherford',
    playByPlay: [
      { id: 'p1', timestamp: '04:12', text: 'Jayden Carter drives left for an explosive transition layup!', team: 'home', points: 2 },
      { id: 'p2', timestamp: '04:45', text: 'Bergen Catholic hits a contested 3-pointer from the wing', team: 'away', points: 3 },
      { id: 'p3', timestamp: '05:10', text: 'Steal by Jayden Carter, assist to Vance for the fastbreak bucket', team: 'home', points: 2 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    id: 'game-202',
    title: 'Tri-State Flag Football Premier Bowl',
    sport: 'Flag Football',
    status: 'Halftime',
    period: 'Halftime',
    gameClock: '00:00',
    isClockRunning: false,
    homeTeam: {
      name: 'Paramus Catholic',
      abbreviation: 'PC',
      score: 21,
      color: '#EC4899',
      timeoutsLeft: 2,
      fouls: 1
    },
    awayTeam: {
      name: 'Hillsborough High',
      abbreviation: 'HIL',
      score: 14,
      color: '#F59E0B',
      timeoutsLeft: 1,
      fouls: 2
    },
    location: 'Iron Peak Sports Complex, Hillsborough',
    playByPlay: [
      { id: 'p10', timestamp: '00:05', text: 'Maya Sanchez throws a 35-yard TD pass to Devon Reed in the back corner!', team: 'home', points: 6 },
      { id: 'p11', timestamp: '00:02', text: '1-point extra point conversion GOOD by PC', team: 'home', points: 1 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    id: 'game-203',
    title: 'Garden State Lacrosse Invitational',
    sport: 'Lacrosse',
    status: 'Live',
    period: '4th Quarter',
    gameClock: '01:45',
    isClockRunning: true,
    homeTeam: {
      name: 'Delbarton School',
      abbreviation: 'DEL',
      score: 11,
      color: '#10B981',
      timeoutsLeft: 1,
      fouls: 2
    },
    awayTeam: {
      name: 'Seton Hall Prep',
      abbreviation: 'SHP',
      score: 10,
      color: '#8B5CF6',
      timeoutsLeft: 1,
      fouls: 3
    },
    location: 'Rutgers Athletics Field, Piscataway',
    playByPlay: [
      { id: 'p20', timestamp: '01:45', text: 'Marcus Vance dodges top-center and fires a 90mph rip into the top corner!', team: 'home', points: 1 }
    ],
    updatedAt: new Date().toISOString()
  }
];

export const INITIAL_VENUES = [
  {
    id: 'venue-101',
    facilityName: 'MetLife Arena & Sports Complex',
    address: '1 MetLife Stadium Dr',
    city: 'East Rutherford',
    state: 'NJ',
    subLocations: ['Court A (Main)', 'Court B', 'Court C', 'Field 1 (Turf)', 'Field 2']
  },
  {
    id: 'venue-102',
    facilityName: 'Iron Peak Sports & Events Center',
    address: '137 Mountain View Rd',
    city: 'Hillsborough',
    state: 'NJ',
    subLocations: ['Indoor Dome 1', 'Indoor Dome 2', 'Outdoor Turf A', 'Outdoor Turf B']
  },
  {
    id: 'venue-103',
    facilityName: 'Rutgers Athletic Center & Fields',
    address: '83 Rockafeller Rd',
    city: 'Piscataway',
    state: 'NJ',
    subLocations: ['Main Stadium', 'Practice Field 1', 'Auxiliary Court 1', 'Auxiliary Court 2']
  }
];

export const INITIAL_TOURNAMENTS = [
  {
    id: 'tourn-301',
    name: 'Tri-State Elite Basketball Showcase 2026',
    sport: 'Basketball' as const,
    startDate: '2026-08-15',
    endDate: '2026-08-17',
    format: 'Single Elimination' as const,
    participatingTeams: [
      'St. Anthony Prep',
      'Bergen Catholic',
      'Paramus Catholic',
      'Seton Hall Prep',
      'Delbarton School',
      'Don Bosco Prep',
      'Camden High',
      'Roselle Catholic'
    ],
    venueId: 'venue-101',
    venueName: 'MetLife Arena & Sports Complex',
    status: 'In Progress' as const,
    createdAt: new Date().toISOString()
  },
  {
    id: 'tourn-302',
    name: 'Garden State Flag Football Championship',
    sport: 'Flag Football' as const,
    startDate: '2026-08-20',
    endDate: '2026-08-22',
    format: 'Single Elimination' as const,
    participatingTeams: [
      'Paramus Catholic',
      'Hillsborough High',
      'Wayne Hills',
      'Old Bridge Blitz',
      'Union City Vipers',
      'Edison Express',
      'Hoboken Titans',
      'Passaic Pride'
    ],
    venueId: 'venue-102',
    venueName: 'Iron Peak Sports & Events Center',
    status: 'Upcoming' as const,
    createdAt: new Date().toISOString()
  },
  {
    id: 'tourn-303',
    name: 'NJ Lax Premier Cup 2026',
    sport: 'Lacrosse' as const,
    startDate: '2026-09-01',
    endDate: '2026-09-03',
    format: 'Pool Play' as const,
    participatingTeams: [
      'Delbarton School',
      'Seton Hall Prep',
      'Summit High',
      'Chatham Elite'
    ],
    venueId: 'venue-103',
    venueName: 'Rutgers Athletic Center & Fields',
    status: 'Upcoming' as const,
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_MATCHES = [
  // Round 1 (Quarterfinals - tourn-301)
  {
    id: 'match-101',
    tournamentId: 'tourn-301',
    round: 1,
    matchNumber: 1,
    homeTeam: 'St. Anthony Prep',
    awayTeam: 'Roselle Catholic',
    homeScore: 78,
    awayScore: 65,
    winner: 'St. Anthony Prep',
    status: 'Completed' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court A (Main)',
    scheduledTime: '2026-08-15 09:00 AM',
    nextMatchId: 'match-201',
    nextMatchSlot: 'home' as const
  },
  {
    id: 'match-102',
    tournamentId: 'tourn-301',
    round: 1,
    matchNumber: 2,
    homeTeam: 'Bergen Catholic',
    awayTeam: 'Camden High',
    homeScore: 71,
    awayScore: 68,
    winner: 'Bergen Catholic',
    status: 'Completed' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court B',
    scheduledTime: '2026-08-15 10:30 AM',
    nextMatchId: 'match-201',
    nextMatchSlot: 'away' as const
  },
  {
    id: 'match-103',
    tournamentId: 'tourn-301',
    round: 1,
    matchNumber: 3,
    homeTeam: 'Seton Hall Prep',
    awayTeam: 'Don Bosco Prep',
    homeScore: 64,
    awayScore: 60,
    winner: 'Seton Hall Prep',
    status: 'Completed' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court C',
    scheduledTime: '2026-08-15 12:00 PM',
    nextMatchId: 'match-202',
    nextMatchSlot: 'home' as const
  },
  {
    id: 'match-104',
    tournamentId: 'tourn-301',
    round: 1,
    matchNumber: 4,
    homeTeam: 'Delbarton School',
    awayTeam: 'Paramus Catholic',
    homeScore: 82,
    awayScore: 75,
    winner: 'Delbarton School',
    status: 'Completed' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court A (Main)',
    scheduledTime: '2026-08-15 01:30 PM',
    nextMatchId: 'match-202',
    nextMatchSlot: 'away' as const
  },

  // Round 2 (Semifinals - tourn-301)
  {
    id: 'match-201',
    tournamentId: 'tourn-301',
    round: 2,
    matchNumber: 1,
    homeTeam: 'St. Anthony Prep',
    awayTeam: 'Bergen Catholic',
    homeScore: 68,
    awayScore: 64,
    winner: '',
    status: 'Live' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court A (Main)',
    scheduledTime: '2026-08-16 02:00 PM',
    nextMatchId: 'match-301',
    nextMatchSlot: 'home' as const
  },
  {
    id: 'match-202',
    tournamentId: 'tourn-301',
    round: 2,
    matchNumber: 2,
    homeTeam: 'Seton Hall Prep',
    awayTeam: 'Delbarton School',
    homeScore: 0,
    awayScore: 0,
    winner: '',
    status: 'Scheduled' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court B',
    scheduledTime: '2026-08-16 04:00 PM',
    nextMatchId: 'match-301',
    nextMatchSlot: 'away' as const
  },

  // Round 3 (Finals - tourn-301)
  {
    id: 'match-301',
    tournamentId: 'tourn-301',
    round: 3,
    matchNumber: 1,
    homeTeam: 'TBD (Winner SF1)',
    awayTeam: 'TBD (Winner SF2)',
    homeScore: 0,
    awayScore: 0,
    winner: '',
    status: 'Scheduled' as const,
    venueId: 'venue-101',
    venueName: 'MetLife Arena',
    subLocation: 'Court A (Main)',
    scheduledTime: '2026-08-17 06:00 PM'
  }
];

export const INITIAL_CHECK_INS = [
  {
    id: 'checkin-1',
    athleteUid: 'user-1',
    athleteName: 'Jayden Carter',
    athletePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    teamName: 'St. Anthony Prep',
    sport: 'Basketball' as const,
    tournamentId: 'tourn-301',
    tournamentName: 'Tri-State Elite Basketball Showcase 2026',
    matchId: 'match-201',
    courtField: 'Court A (Main)',
    status: 'Checked In' as const,
    checkInTime: new Date(Date.now() - 1000 * 60 * 25).toISOString()
  },
  {
    id: 'checkin-2',
    athleteUid: 'user-2',
    athleteName: 'Marcus Vance',
    athletePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    teamName: 'Delbarton School',
    sport: 'Lacrosse' as const,
    tournamentId: 'tourn-303',
    tournamentName: 'NJ Lax Premier Cup 2026',
    matchId: 'match-202',
    courtField: 'Court B',
    status: 'Checked In' as const,
    checkInTime: new Date(Date.now() - 1000 * 60 * 10).toISOString()
  },
  {
    id: 'checkin-3',
    athleteUid: 'user-3',
    athleteName: 'Maya Sanchez',
    athletePhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    teamName: 'Paramus Catholic',
    sport: 'Flag Football' as const,
    tournamentId: 'tourn-302',
    tournamentName: 'Garden State Flag Football Championship',
    matchId: 'match-104',
    courtField: 'Outdoor Turf A',
    status: 'Pending' as const,
    checkInTime: ''
  }
];

